# New PhD Application
# Basic Details
SELF = "SELF"
DTP = "DTP"
CDT = "CDT"
PROJECT = "PROJECT"
XSCHOLARSHIP = "XSCHOLARSHIP"
DOC = "DOC"
OTHER = "OTHER"

PENDING = "PENDING"
AWARDED = "AWARDED"

HOME = "HOME"
EU = "EU"
OVERSEAS = "OVERSEAS"
QUERY = "QUERY"

COMPUTING = "COMPUTING"
CDT_STUDENT = "CDT"
COMPUTING_AND_CDT = "COMPUTING_AND_CDT"

PENDING_STATUS = "PENDING"
ACCEPTED = "ACCEPTED"
REJECTED = "REJECTED"
WITHDRAWN = "WITHDRAWN"
REJECT_TO_MSC = "REJECT_TO_MSC"
