# New PhD Application
# Basic Details
SELF = "SELF"
DTP = "DTP"
CDT = "CDT"
PROJECT = "PROJECT"
XSCHOLARSHIP = "XSCHOLARSHIP"
DOC = "DOC"
OTHER = "OTHER"

PENDING = "PENDING"
AWARDED = "AWARDED"

HOME = "HOME"
EU = "EU"
OVERSEAS = "OVERSEAS"
QUERY = "QUERY"

COMPUTING = "COMPUTING"
CDT_STUDENT = "CDT"
COMPUTING_AND_CDT = "COMPUTING_AND_CDT"
