# User roles
ADMIN = "ADMIN"
SUPERVISOR = "SUPERVISOR"
SUPER_ADMIN = "SUPER_ADMIN"

# New PhD Application
# Basic Details
SELF = "SELF"
DTP = "DTP"
CDT = "CDT"
PROJECT = "PROJECT"
XSCHOLARSHIP = "XSCHOLARSHIP"
DOC = "DOC"
OTHER = "OTHER"

PENDING = "PENDING"
AWARDED = "AWARDED"

HOME = "HOME"
EU = "EU"
OVERSEAS = "OVERSEAS"
QUERY = "QUERY"

COMPUTING = "COMPUTING"
CDT_STUDENT = "CDT"
COMPUTING_AND_CDT = "COMPUTING_AND_CDT"

PENDING_STATUS = "PENDING"
ACCEPTED = "ACCEPTED"
REJECTED = "REJECTED"
WITHDRAWN = "WITHDRAWN"
REJECT_TO_MSC = "REJECT_TO_MSC"
DEFERRED = "DEFERRED"

# Supervision
NOT_VIEWED = "NOT_VIEWED"
WAIT_TO_INTERVIEW = "WAIT_TO_INTERVIEW"
REJECT_TO_MSC_RECOMMEND = "REJECT_TO_MSC"
REJECT_TO_MAC_RECOMMEND = "REJECT_TO_MAC"
STRAIGHT_REJECT = "STRAIGHT_REJECT"
ACCEPT_BUT_NOT_SUPERVISED = "ACCEPT_BUT_NOT_SUPERVISED"
ACCEPT_AND_SUPERVISED = "ACCEPT_AND_SUPERVISED"
OTHER_RECOMMEND = "OTHER"

# Documentation
APPLICATION_FORM = "APPLICATION_FORM"
RESEARCH_SUMMARY = "RESEARCH_SUMMARY"
REFERENCE = "REFERENCE"
ADDITIONAL_MATERIAL = "ADDITIONAL_MATERIAL"
